<main>
    @include('sections.banner')
    @include('sections.feature')
    @include('sections.about')
    @include('sections.blog')
    @include('sections.instructor')
    @include('sections.catrgory')
    @include('sections.choose')
    @include('sections.counter')
    @include('sections.testimonial')
    @include('sections.brand')
</main>
